### ISSUE TITLE
flutter sdk integration issue

### ISSUE THREAD

**Issue by mohib-raja11** [talsec/Free-RASP-Flutter#1]
Why I'm getting following issue when I integrate Free-RSAP sdk. I have fixed it by implementing the code which was in guide of android setup then integration issue gone fixed , app is runnable but not working fine. 

![image](https://user-images.githubusercontent.com/79722707/133251807-1536d44b-1784-4169-aac2-8115c4e1a9f3.png)

**Comment by mohib-raja11** [comment]
Dear contributors, I had fixed this issue using android configuration too in flutter. If we should configuration in build.gradle file than you should also enlist them in flutter guide.


Anyhow my new questions is that how we have to work this api?
I successfully integrated and callbacks also invoke on special actions i.e. emulator or rooted device.
How I have to secure my app from reverse engineering or what i have to do?

**Comment by talsec-app** [comment]
Hello.  
Unfortunately, we are not able to reproduce your problem. Anyway, we will add your solution to documentation until further investigation is not done.  
Reactions for each detection are fully handled by developer. We'll try to come up with some recommendations on how application should behave when certain threat is detected.
