### ISSUE TITLE
Build module Fail in IOS

### ISSUE THREAD

**Issue by neroaCu** [talsec/Free-RASP-Flutter#10]
Hi, I install this plugin but it failed to compile.

here is the error message

Failed to build module 'TalsecRuntime' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

 Flutter (Channel stable, 2.5.0, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode12.5.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

Could you please help? thanks

**Comment by talsec-app** [comment]
Hello
Thank you for your report.
We are aware of the issue and we are actively looking for solution.
Talsec Team

**Comment by neroaCu** [comment]
Thanks.

Additional information

Users/xxxxxx/Documents/flutter2.5.0/.pub-cache/hosted/pub.dartlang.org/freerasp-1.1.0/ios/Classes/SwiftFreeraspPlugin.swift:3:8: error: failed to build module 'TalsecRuntime' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'
    import TalsecRuntime
           ^
    /Users/xxxxxx/Documents/acupay/build/ios/Debug-iphoneos/XCFrameworkIntermediates/TalsecRuntime/TalsecRuntime.framework/Modules/TalsecRuntime.swiftmodule/arm64-apple-ios.swiftinterface:11:8: error: no such module '_Concurrency'
    import _Concurrency

**Comment by talsec-app** [comment]
After analysis, we come to conclusion that old version of Xcode is causing the trouble.

Because of some security features, our freeRASP framework for iOS (which Flutter plugin use under the hood) is build for Xcode 13. Your version of Xcode is 12.5 so its unable to compile whole project because of it. To keep security features intact, we are unable to compile for lower version of Xcode. **In order to use freeRASP (at least for iOS) update your Xcode to version 13.** 

To prevent further confution in the future, README will be updated and information about Xcode version will be added.

If issue persists, please let us know
Talsec Team

**Comment by neroaCu** [comment]
Thank you so much for such a quick reply.

I will verify if xcode 13 works or not. Then i'll update it here.

**Comment by neroaCu** [comment]
sorry, for late reply.

Xcode 13 work well. Thanks @talsec-app
