### ISSUE TITLE
Android build fails since March 4th, 14 o'clock

### ISSUE THREAD

**Issue by timobaehr** [talsec/Free-RASP-Flutter#104]
**Describe the bug**

Android build fails for task ':app:mergeReleaseResources'. 

```
Could not GET 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.0.0/TalsecSecurity-Community-Flutter-9.0.0.pom'. Received status code 503 from server: Service Unavailable
```

**To Reproduce**
Try to build a Flutter app with `freerasp` plugin with empty cache.

**Expected behavior**
https://nexus3-public.monetplus.cz should answer and provide the sources.

**Please complete the following information:**
 - Device: Mac mini M1
 - Version of freeRASP: 6.3.0, 6.4.0

**Comment by timobaehr** [comment]
https://nexus3-public.monetplus.cz is now available again.

**Comment by yardexx** [comment]
Hello.

Apologies for the inconvenience. We'll keep an eye on the Nexus server.

Jaroslav from Talsec Team

**Comment by timobaehr** [comment]
> Hello.
> 
> Apologies for the inconvenience. We'll keep an eye on the Nexus server.
> 
> Jaroslav from Talsec Team

Thank you very much for the quick response and thank you for your good work!
