### ISSUE TITLE
bug: Typecast error (int to String) in debug mode

### ISSUE THREAD

**Issue by provRushabhShah** [talsec/Free-RASP-Flutter#105]
**Describe the bug**

**To Reproduce**
If applicable, steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Device: [e.g. Samsung Galaxy A50]
 - OS version: [e.g. Android 12]
 - Version of freeRASP: [e.g. 6.0.0]

**Additional context**

**Comment by msikyna** [comment]
Hello @provRushabhShah ,
could you please provide more details about the issue? Ideally stacktrace.

Kind regards,
Talsec team

**Comment by yardexx** [comment]
Hello, @provRushabhShah 

Are you using freerasp plugin from GitHub? If so, could you try to use one from pub.dev? Seems like we mixed up versions here on GitHub.

**Comment by tompsota** [comment]
Closing this, as the issue has been resolved in [freeRASP 6.5.0](https://github.com/talsec/Free-RASP-Flutter/releases/tag/v6.5.0).
