### ISSUE TITLE
bug: PlatformException - dlopen failed: library "libsecurity.so" not found

### ISSUE THREAD

**Issue by chongmengkuan** [talsec/Free-RASP-Flutter#107]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.UnsatisfiedLinkError, dlopen failed: library "libsecurity.so" not found, null, null)
Any idea on this?

**Comment by yardexx** [comment]
Hello @chongmengkuan.

Thanks for raising this issue. Can you provide full stacktrace of error? 

Thanks.

**Comment by karlisparcell** [comment]
I also got this error just on an emulator. A build seems to run fine
Error was raised on this emulator 
Pixel_4_API_30  • Pixel 4 API 30  • Google • android
This is a google play emulator. 
But didn't happen on a 
Pixel_4a_API_31 • Pixel 4a API 31 • Google • android
Non google play emulator.

Not sure if google play has anything to do with it or the android version

Flutter version
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (6 days ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1


Stack trace 
E/flutter ( 3476): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.UnsatisfiedLinkError, dlopen failed: library "libsecurity.so" not found, null, null)
E/flutter ( 3476): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3476): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3476): <asynchronous suspension>
E/flutter ( 3476): #2      main (package:obscured/main.dart:46:3)
E/flutter ( 3476): <asynchronous suspension>

Hope this may help

**Comment by msikyna** [comment]
Hello @chongmengkuan , @karlisparcell ,

could you check if the solution proposed in this issue (https://github.com/talsec/Free-RASP-Android/issues/18#issuecomment-1667376785) helps to resolve your problem?

Kind regards,
Talsec team
