### ISSUE TITLE
Device Id Issue

### ISSUE THREAD

**Issue by bruzzers** [talsec/Free-RASP-Flutter#108]
Hi all, 

Every time I do a first installation on iOS device onDeviceId callback is called. When I reinstall it everything is fine, I have to manage first installation? 

Thank you.

**Comment by msikyna** [comment]
Hello @bruzzers ,
The onDeviceId detects, whether the device identifier (identifierForVendor) has been changed. It can be triggered after reinstallation of the application if there are none other applications from the same vendor installed. What is meant by "every time I do a first installation"? Is it happening on more devices?

Kind regards,
Talsec team

**Comment by bruzzers** [comment]
Hello @msikyna, 
the callback is called only on the first installation, when device hasn't my app installed and not on reinstallation. It happens on all iOS devices, physical and simulator.
