### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by m-akbarfauzi** [talsec/Free-RASP-Flutter#118]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 19s
[!] Gradle threw an error while downloading artifacts from the network.
Error: Gradle task assembleDebug failed with exit code 1

**Comment by m-akbarfauzi** [comment]
![Screenshot 2024-06-16 at 22 00 04](https://github.com/talsec/Free-RASP-Flutter/assets/57854089/465a43b8-8936-4c70-98cc-ad5dbeccaeef)

**Comment by msikyna** [comment]
Hello @m-akbarfauzi ,
thank you for reporting the issue, it has been solved.

Kind regards,
Talsec team
