### ISSUE TITLE
onTamperDetected is executed when running on physical device

### ISSUE THREAD

**Issue by neroaCu** [talsec/Free-RASP-Flutter#12]
Hi,

Can you tell me under what conditions this plugin would detect it as a tampering case? 

I enabled this onTamperDetected feature in android and found that it was invoked on a physical device (developer mode is enable) and simulator as well.  Is this expected behaviour? for example, it restricts the app must be download from google/Apple Store? 

Or does it means I did something else wrong? like the **expectedSigningCertificateHash** is wrong? 

Please help. Thanks

**Comment by talsec-app** [comment]
Hello,

application is considered tampered if it has incorrect package name or if it was signed/resigned with an unknown signing key (signing certificate mismatch). If the application is installed from an untrusted application store, onUntrustedInstallationDetected is triggered. Please verify, that your expectedSigningCertificateHash is correct. You can use this link for Base64 -> Hex conversion: https://base64.guru/converter/decode/hex
We will try to add expectedSigningCertificateHash checks to the next version of Talsec.

Talsec Team

**Comment by rakesh0689** [comment]
onPackageTamperDetected is getting called when I am installing the release build in emulator as well as real device. I have certain doubt regarding the expectedSigningCertificateHash. 

1. sha256 value is in the format 'xx:xx:xx:xx:xx' right? So should we covert that to Base64 format?
2. I converted to Base64. format using the code base64.encode(utf8.encode(xx:xx:xx:xx:xx)). Is it the right way?
3. The above link provided converts base64 to hex value and I am not getting back mu sha256 value from the encoded one. So should I convert sha256 to hex and then hex to base64?

Please revert at the earliest as I am wanna make sure all the checks works before continuing my work. Thanks is advance.
