### ISSUE TITLE
Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.

### ISSUE THREAD

**Issue by Charles045** [talsec/Free-RASP-Flutter#128]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
               > Connect to nexus3-public.monetplus.cz:443 [nexus3-public.monetplus.cz/193.33.22.168] failed: Connect timed out
   > Could not resolve com.mob:MobLink:+.
     Required by:
         project :app
      > Failed to list versions for com.mob:MobLink.
         > Unable to load Maven meta-data from https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml'.
               > Connect to europe-west3-maven.pkg.dev:443 [europe-west3-maven.pkg.dev/142.250.99.82] failed: Connect timed out

my flutter app config:
android -> build.gradle
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.3.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.mob.sdk:MobSDK2:+"
        classpath "com.huawei.agconnect:agcp:1.8.0.300"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
        maven { url "https://storage.googleapis.com/download.flutter.io" }
        maven { url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp" }
        maven { url 'https://www.jitpack.io' }
    }
}

how to resolve this issue?

**Comment by msikyna** [comment]
Hello,
how did you integrated the freeRASP? The `maven { url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp" }` should not be in the gradle of your app. 

Did you install the plugin using `flutter pub add freerasp`, exactly as [described in the documentation](https://docs.talsec.app/freerasp/integration/flutter#install-the-plugin)? 

Kind regards,
Talsec team

**Comment by Charles045** [comment]
first, thanks msikyna replies.

I integrated the freeRASP plugin for flutter, in my pubspec.yaml file:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sentry_flutter: ^8.7.0
  sentry_dio: ^8.7.0
  freerasp: ^6.6.0

android -> app -> build.gradle configs:
android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.xxxxxxxx.xxx"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }
}

android -> build.gradle configs:

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.3.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.mob.sdk:MobSDK2:+"
        classpath "com.huawei.agconnect:agcp:1.8.0.300"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
        maven { url "https://download.flutter.io" }
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

after the flutter pub get is executed, I runs in the android device,  the following issue occurs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mob:MobLink:+.
     Required by:
         project :app
      > Failed to list versions for com.mob:MobLink.
         > Unable to load Maven meta-data from https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml'.
               > Connect to europe-west3-maven.pkg.dev:443 [europe-west3-maven.pkg.dev/142.250.99.82] failed: Connect timed out
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://download.flutter.io/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://download.flutter.io/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
               > Certificate for <download.flutter.io> doesn't match any of the subject alternative names: [*.storage.googleapis.com, *.googleapis.com, commondatastorage.googleapis.com, *.commondatastorage.googleapis.com, storage.googleapis.com, storage-p2.googleapis.com, *.storage-p2.googleapis.com, storage.mtls.googleapis.com, *.appspot.com.storage.googleapis.com, *.content-storage.googleapis.com, *.content-storage-p2.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage-download.googleapis.com]
      > Skipped due to earlier error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

I checked some  similar troubles resolved by append the maven { url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp" } or  In android -> app -> build.gradle add these dependencies

dependencies {
   implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:<version>'
}

I tried to alter it, but still can't resolved this trouble. I hope you can  give me some help or advice, thanks again.

**Comment by yardexx** [comment]
Hello @Charles045 

We deprecated Nexus deployment in [freeRASP version 6.5.1](https://github.com/talsec/Free-RASP-Flutter/blob/master/CHANGELOG.md#android-1), so the fix you implemented is invalid. Although I can't replicate the issue locally, the logs suggest that Gradle is attempting to locate the MobLink dependency in our Maven repository.

Could you please provide a list of all the dependencies you're using? Specifically, I need:
- Flutter dependencies (from pubspec.yaml -> dependencies)
- Android dependencies (from android/app/build.gradle -> dependencies section at the bottom)

Kind regards,
Jaroslav from Talsec Team

**Comment by Charles045** [comment]
Thanks yardexx for your replied! 

Here is my flutter project dependencies and android build.gradle configurations:

pubspec.yaml -> dependencies

`
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  event_bus: ^2.0.0
  fluro: ^2.0.5
  dio: ^5.5.0
  protobuf: ^3.1.0
  connectivity_plus: ^6.0.4
  encrypt: ^5.0.3
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  pull_to_refresh: ^2.0.0
  webview_flutter: ^4.8.0
  flutter_staggered_grid_view: ^0.7.0
  extended_nested_scroll_view: ^6.2.1
  flutter_draggable_gridview: ^0.0.12
  card_swiper: ^3.0.1
  qr_flutter: ^4.1.0
  easy_pdf_viewer: ^1.0.8
  wechat_assets_picker: ^9.1.0
  extended_image: ^8.2.1
  flutter_svg_provider: ^1.0.7
  signature: ^5.5.0
  sentry_flutter: ^8.7.0
  sentry_dio: ^8.7.0
  freerasp: ^6.6.0
  fluwx: ^4.5.5
  tobias: ^4.0.0
  mobcommonlib: ^1.1.5
  mobpush_plugin: ^1.2.5
  moblink: ^3.4.7
`

android/settings.gradle:

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
        gradlePluginPortal()
    }
}


plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

include ":app"


android/build.gradle

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
    }
    dependencies {
        classpath "com.mob.sdk:MobSDK2:+"
        classpath "com.huawei.agconnect:agcp:1.8.0.300"
        classpath "com.android.tools.build:gradle:7.3.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
        maven { url "https://download.flutter.io" }
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


android/app/build.gradle

plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0.0'
}

apply plugin: 'com.mob.sdk'
apply plugin: 'com.huawei.agconnect'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def dartEnvDefines = [
        CHANNEL: '',
        ENV    : '',
]

if (project.hasProperty('dart-defines')) {
    dartEnvDefines = project.property('dart-defines')
            .split(',')
            .collectEntries { entry ->
                def pair = new String(entry.decodeBase64(), 'UTF-8').split('=')
                [(pair.first()): pair.last()]
            }
}

android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.xxxxxxxx.yyyy"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            zipAlignEnabled true
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            shrinkResources false
            minifyEnabled false
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def channelName = dartEnvDefines.CHANNEL
            if (channelName == null) {
                channelName = 'debug'
            }
            def newApkName = "ggb_${channelName.toLowerCase()}_${dartEnvDefines.ENV}_${flutterVersionName}_${flutterVersionCode.toInteger()}.apk"
            println('apk:' + newApkName)
            outputFileName = new File(newApkName)
        }
    }
}

flutter {
    source '../..'
}

MobSDK {
    appKey "xxxxxxxxxxxx"
    appSecret "xxxxxxxxxxxxxxxxxxxxxx"
    MobPush {
        devInfo {
            HUAWEI {
                appId "ddxxxxxx"
            }
            ...
        }
    }
    MobLink {
        uriScheme "xxxxxxxxxx"
        appLinkHost "xxxx.cn"
    }
}

build failed information:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mob:MobLink:+.
     Required by:
         project :app
      > Failed to list versions for com.mob:MobLink.
         > Unable to load Maven meta-data from https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/mob/MobLink/maven-metadata.xml'.
               > Connect to europe-west3-maven.pkg.dev:443 [europe-west3-maven.pkg.dev/142.250.99.82, europe-west3-maven.pkg.dev/2404:6800:4008:c1b:0:0:0:52] failed: Connect timed out
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://download.flutter.io/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://download.flutter.io/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
               > Certificate for <download.flutter.io> doesn't match any of the subject alternative names: [*.storage.googleapis.com, *.googleapis.com, commondatastorage.googleapis.com, *.commondatastorage.googleapis.com, storage.googleapis.com, storage-p2.googleapis.com, *.storage-p2.googleapis.com, storage.mtls.googleapis.com, *.appspot.com.storage.googleapis.com, *.content-storage.googleapis.com, *.content-storage-p2.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage-download.googleapis.com]
      > Skipped due to earlier error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 38s
[!] Gradle threw an error while downloading artifacts from the network.

**Comment by Charles045** [comment]
I tried to run the project of [Free-RASP-Flutter](https://github.com/talsec/Free-RASP-Flutter) example

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
               > Connect to europe-west3-maven.pkg.dev:443 [europe-west3-maven.pkg.dev/74.125.142.82] failed: Connect timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
[!] Gradle threw an error while downloading artifacts from the network.

**Comment by Charles045** [comment]
I tried to run the project of [Free-RASP-Flutter](https://github.com/talsec/Free-RASP-Flutter) example

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Required by:
         project :app > project :freerasp
      > Could not resolve com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
         > Could not get resource 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
            > Could not GET 'https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom'.
               > Connect to europe-west3-maven.pkg.dev:443 [europe-west3-maven.pkg.dev/74.125.142.82] failed: Connect timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
[!] Gradle threw an error while downloading artifacts from the network.

**Comment by Charles045** [comment]
**FAILURE: Build failed with an exception.**


* What went wrong:

Execution failed for task ':app:checkDebugAarMetadata'.

> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.

> The project declares repositories, effectively ignoring the repositories you have declared in the settings.

> You can figure out how project repositories are declared by configuring your build to fail on project repositories.

* See https://docs.gradle.org/7.5/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.

   > Could not find com.aheaditec.talsec.security:TalsecSecurity-Community-Flutter:9.6.0.
     Searched in the following locations:

       - https://plugins.gradle.org/m2/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom
       - https://dl.google.com/dl/android/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom
       - https://repo.maven.apache.org/maven2/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom
       - https://mvn.mob.com/android/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom
       - https://developer.huawei.com/repo/com/aheaditec/talsec/security/TalsecSecurity-Community-Flutter/9.6.0/TalsecSecurity-Community-Flutter-9.6.0.pom

     Required by:
         project :app > project :freerasp

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.


* **my flutter project config file info:**

* project/android/settings.gradle

pluginManagement {

    def flutterSdkPath = {

        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath

    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {

        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://storage.flutter-io.cn/download.flutter.io" }
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }

    }
}

plugins {

    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false

}

dependencyResolutionManagement {

    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {

        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://storage.flutter-io.cn/download.flutter.io" }
        maven { url "https://mvn.mob.com/android" }
        maven { url "https://developer.huawei.com/repo/" }
    }
}

include ":app"

* project/android/build.gradle

buildscript {
    ext.kotlin_version = '1.7.10'
    dependencies {
        classpath "com.android.tools.build:gradle:7.3.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.mob.sdk:MobSDK2:+"
        classpath "com.huawei.agconnect:agcp:1.8.0.300"
    }
}

plugins {
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by yardexx** [comment]
Hello.

I've tried to replicate the issue but with no luck. From what I can see in your Gradle dependencies, a some sort of geolocation blocking or VPN could be source of an issue.

Kind regards,
Jaroslav from Talsec
