### ISSUE TITLE
Package not working for me

### ISSUE THREAD

**Issue by AhmedHammad0900** [talsec/Free-RASP-Flutter#13]
I am interested in this package

I used it as follows in documntion but it detected nothing ..

I used SHA1 that I got from gradlew signingReport command so I am not sure if it's the right way
it was under the following lines
```
 Task :app:signingReport
Variant: debug
Config: debug
Store: C:\Users\myuserhere\.android\debug.keystore
Alias: AndroidDebugKey
MD5: here is md5
SHA1: here is the one I used ..
```
![image](https://user-images.githubusercontent.com/81931290/156824624-28d7f291-07d2-40a7-aac8-bab2406864c2.png)

![image](https://user-images.githubusercontent.com/81931290/156824639-dfd53e8a-7491-4579-ac98-7798731a75c7.png)
`
![image](https://user-images.githubusercontent.com/81931290/156824098-4a54ec94-e45b-4f10-94b5-cb444e0c716b.png)
![image](https://user-images.githubusercontent.com/81931290/156824145-32309052-3a78-41b1-a371-85c495abd902.png)
![image](https://user-images.githubusercontent.com/81931290/156824244-ef4cee5e-2509-4a84-b117-3a2c68bdb316.png)

- * Result on Emulator for app-relase Memu Emulator * 

![image](https://user-images.githubusercontent.com/81931290/156824466-04453d51-b88e-456c-9de7-fe9fdf23762b.png)

I did something wrong or there is a problem that emualtor not getting detected ? I know there is a different between debug and relase but not understanding if I did mistake relayed to that ... not professional to know that details

**Comment by talsec-app** [comment]
Hello AhmedHammad0900.
Did you start Talsec using `app.start()`  after providing `config` and `callback` in `TalsecApp`? It is not visible in your code snipets.
Talsec Team

**Comment by AhmedHammad0900** [comment]
> Hello AhmedHammad0900. Did you start Talsec using `app.start()` after providing `config` and `callback` in `TalsecApp`? It is not visible in your code snipets. Talsec Team

Yea I started it and got in Terminal , it worked for a while and stopped working and the problem is back in already Relased app idk how it happened ?

`E/flutter (18753): #8      TalsecApp.start (package:freerasp/talsec_app.dart:66:5)`

**Comment by talsec-app** [comment]
Please verify that you notified the framework that the internal state of those strings has changed by calling setState:
```js
onRootDetected: () => {
  Root = 'Root detected';
  setState(() {});
}
```
If the issue persists, please let us know. You can email us at info@talsec.app so we can look into it together.

Talsec Team

**Comment by AhmedHammad0900** [comment]
> Please verify that you notified the framework that the internal state of those strings has changed by calling setState:
> 
> ```js
> onRootDetected: () => {
>   Root = 'Root detected';
>   setState(() {});
> }
> ```
> 
> Also check [#11 (comment)](https://github.com/talsec/Free-RASP-Flutter/issues/11#issuecomment-1055250491) if it helps you.
> 
> If the issue persists, please let us know. You can email us at [info@talsec.app](mailto:info@talsec.app) so we can look into it together.
> 
> Talsec Team

yea it was about setstate ty alot <3
but It don't work on IOS I am getting alot of errors ,, I edited scheme and added the script , also changed confirgations to recommended one for pods and runnder still getting the error

![image](https://user-images.githubusercontent.com/81931290/163495456-e572817f-ace7-4faf-924b-be396b7a1139.png)

**Comment by talsec-app** [comment]
Hello @AhmedHammad0900, we are sorry for the late response. Does the issue still persist? Could you elaborate more on exactly what errors (stack trace or screenshot)?

Are you trying to build the debug or release version? There is an issue with the release version not being able to run in Xcode Simulators (https://docs.flutter.dev/testing/build-modes#release)
