### ISSUE TITLE
Warning when build a IPA for apple ios

### ISSUE THREAD

**Issue by JgomesAT** [talsec/Free-RASP-Flutter#133]
The archive did not include a dSYM for the TalsecRuntime.framework with the UUIDs [FBD6456F-EE78-3031-A883-EA261BEB37DB]. Ensure that the archive's dSYM folder includes a DWARF file for TalsecRuntime.framework with the expected UUIDs.

**Comment by zakka258** [comment]
I got this error too. I couldnt upload the app with the symbol to TestFlight via xcode

**Comment by tompsota** [comment]
Hi @JgomesAT, @zakka258,

we'll be publishing a new release this week with the dSYM folder included.

Regards,
Tomas from Talsec

**Comment by msikyna** [comment]
Hello @JgomesAT , @zakka258 ,

a new release has been published. The dSYMs are contained as an Asset in the Release here: https://github.com/talsec/Free-RASP-Flutter/releases/tag/v6.7.0

Let us please know, if it helped. Thank you!

Kind regards,
Talsec team

**Comment by JgomesAT** [comment]
HOw Can I add this dSYMs in my code?

**Comment by msikyna** [comment]
Hello @JgomesAT ,
you can use standard approaches as for other frameworks.

Kind regards,
Talsec team

**Comment by zrpra** [comment]
> Hello,
> 
> I generate a xarchive with xcode and before upload it, I edit the xarchive(show content) and paste the TalsecRuntime.framework.dSYM inside this, and after that I upload to Apple store

Thank you! Passed the validation now, thanks a lot

**Comment by JgomesAT** [comment]
now the erro is different id
The archive did not include a dSYM for the TalsecRuntime.framework with the UUIDs [4EDE8860-AEDC-3C03-808F-EF927DD05A0D]. Ensure that the archive's dSYM folder includes a DWARF file for TalsecRuntime.framework with the expected UUIDs.

**Comment by msikyna** [comment]
Hello @JgomesAT ,
thank you for the collaboration. Regarding the new issue, does it happen also with the new version and the associated dSYMs? https://github.com/talsec/Free-RASP-Flutter/releases/tag/v6.9.0 .. each new version, can have different dSYMs if there is a newer version of the iOS SDK.

Kind regards,
Talsec team

**Comment by JgomesAT** [comment]
Hello,

Now I have this error:

The archive did not include a dSYM for the TalsecRuntime.framework with the UUIDs [4EDE8860-AEDC-3C03-808F-EF927DD05A0D]. Ensure that the archive's dSYM folder includes a DWARF file for TalsecRuntime.framework with the expected UUIDs.
