### ISSUE TITLE
Hooking not working as described

### ISSUE THREAD

**Issue by AhmedHammad0900** [talsec/Free-RASP-Flutter#135]
**Describe the bug**
the Hook security isn't working probably , all devices even un-rooted devices , normal software is detected to have hooking , Idk I think hook is referring to servers that works on mobiles liek Frida , but on all normal mobiles all of them detected to have hook so can u explain if hooking includes another thing that makes all devices to be detected as a hook ? , other features works fine as I tested .

**Please complete the following information:**
 - Device: [All ( Realme 8 , Samsung A51 , Xamoi ]
 - OS version: [e.g. Android All]
 - Version of freeRASP: [e.g. 6.7.0]

**Additional context**

**Comment by MaxSchilling** [comment]
Same here, receiving false positives for onhooks since 6.7.0 on Android (did not test iOS yet)

**Comment by bzkrterdm** [comment]
The 6.7.0 version crashes Android apps, but iOS works.

**Comment by msikyna** [comment]
Hello everyone,

thank you for notifying us promptly. We apologize for the issue. A new patch version has been released: 6.7.1, which solves it.

Kind regards,
Talsec team
