### ISSUE TITLE
Support Android NDK 27b

### ISSUE THREAD

**Issue by jozefvodicka** [talsec/Free-RASP-Flutter#139]
**Describe the bug**
We experience ANR with Gradle 8.7 and NDK 27b and Freerasp 6.7.1, 6.7.0, 6.6.0; 
On NDK 26 and Gradle 7 all was fine;

Have you tried to compile a Flutter Android app with latest Gradle 8.7 and NDK 27b?

Is it running well or do you also experience ANR?

**Comment by msikyna** [comment]
Hello @jozefvodicka ,
we are currently working on the issue. Thank you for reporting it!

Kind regards,
Talsec team

**Comment by jozefvodicka** [comment]
Do you already know whether gradle or ndk caused the issue? If more logs needed, feel free to request it

**Comment by tompsota** [comment]
Hi @jozefvodicka,

this issue might be in fact related to #138, we are investigating the root cause at the moment. Currently, we have enough data, but thanks for your offer! We will let you know when we have any updates. 

Best,
Tomas from Talsec

**Comment by msikyna** [comment]
Hello @jozefvodicka,
the issue has been solved in the new version: 6.7.2.

Kind regards,
Talsec team
