### ISSUE TITLE
False positive issue within the "onHooks" callback

### ISSUE THREAD

**Issue by yamin-elmakis** [talsec/Free-RASP-Flutter#144]
**Describe the bug**
we are running our app with freeRASP and we are using entrust SDK for android (https://www.entrust.com/products/digital-card-solution) and we keep getting callbacks from the "onHooks", while the same code in iOS not (not using entrust SDK).

**To Reproduce**
If applicable, steps to reproduce the behavior.

**Expected behavior**
the "onHooks" callback should be called.

**Screenshots**
just a log of. the "onHooks" callback.

**Please complete the following information:**
 - Device: android devices
 - OS version: minSdkVersion 23
 - Version of freeRASP: freerasp 6.7.2

**Additional context**

**Comment by xprikryl2** [comment]
Hello @yamin-elmakis,

Could you please share the package name or your watcher mail with us? You can send it to [support@talsec.app](support@talsec.app) together with the link to this issue. This will greatly help us identify your application and further investigate. Thank you.

Best regards,
Ondrej from Talsec

**Comment by yamin-elmakis** [comment]
looks like a mistake on my side and the freeRASP version was 6.5.0 and it is fixed in version 6.7.2.
Thank you
