### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: Unexpected end of document

### ISSUE THREAD

**Issue by AwaisQazii** [talsec/Free-RASP-Flutter#147]
**Describe the bug**

Cannot read /data/user/0/com.example.myapp/shared_prefs/LpT9bkPsuUdwEpc29u1gLRB8rwFE7rJAGDTZR6FxVd7z.xml
W/SharedPreferencesImpl(18119): org.xmlpull.v1.XmlPullParserException: Unexpected end of document

**To Reproduce**
on initialization

void main()async{

 final callback = ThreatCallback(
    onPrivilegedAccess: () async {
      controller.isThreatDetected.value = true;
      await prefs.clear();
      await StorageService.instance.deleteAll();
      controller.threatName.value =
          "Unauthorized modifications (root/jailbreak) have been detected on your device";
    },
    onHooks: () async {
      controller.isThreatDetected.value = true;
      await prefs.clear();
      await StorageService.instance.deleteAll();
      controller.threatName.value = "Hooking activities detected";
    },
  );

Talsec.instance.attachListener(callback);

 final config = TalsecConfig(
    androidConfig: androidConfig,
    iosConfig: iOSConfig,
    watcherMail: email,
  );
  await Talsec.instance.start(config);

///my Code
}
**Expected behavior**
No exception should be thrown

**Please complete the following information:**
 - Device: Redmi Note 13
 - OS version: Android 14
 - Version of freeRASP:  freerasp: ^6.7.3

**Comment by msikyna** [comment]
Hello, @AwaisQazii ,

this is a duplicate of this issue https://github.com/talsec/Free-RASP-Flutter/issues/120. We have it in our backlog to fix it.

Kind regards,
Talsec team

**Comment by AwaisQazii** [comment]
Got it. Thank you for prompt response and support. I'm deleting this issue
