### ISSUE TITLE
V6.10.0 not working??

### ISSUE THREAD

**Issue by Omkar6652** [talsec/Free-RASP-Flutter#154]
**Describe the bug**
New version 6.10.0 is not compiling ?

**To Reproduce**
get latest version of freerasp

**Screenshots**

**Please complete the following information:**

 - Version of freeRASP: [6.10.0]

**Additional context**
e: file:///C:/Users/AppData/Local/Pub/Cache/hosted/pub.dev/freerasp-6.10.0/android/src/main/kotlin/com/aheaditec/freerasp/handlers/MethodCallHandler.kt:78:9 Unresolved reference: TalsecThreatHandler
e: file:///C:/Users/AppData/Local/Pub/Cache/hosted/pub.dev/freerasp-6.10.0/android/src/main/kotlin/com/aheaditec/freerasp/handlers/MethodCallHandler.kt:91:9 Unresolved reference: TalsecThreatHandler
e: file:///C:/Users/AppData/Local/Pub/Cache/hosted/pub.dev/freerasp-6.10.0/android/src/main/kotlin/com/aheaditec/freerasp/handlers/MethodCallHandler.kt:134:17 Unresolved reference: TalsecThreatHandler

**Comment by tompsota** [comment]
@Omkar6652 ,

I could not reproduce the issue, just verified the pub.dev plugin and the referenced file is there. Can you try reinstalling the plugin? Also please ensure that the cache is cleared.

Regards,
Tomas

**Comment by Omkar6652** [comment]
ok it works now. only clearing cache didnt seem to work somehow had restart everything... anyways thanks .
