### ISSUE TITLE
dSYMs.zip for last version 6.10

### ISSUE THREAD

**Issue by JgomesAT** [talsec/Free-RASP-Flutter#156]
Could you provide the dSYMs for thsi last version 6.10

**Comment by tompsota** [comment]
Hi @JgomesAT,

Sure. Added them to the release: https://github.com/talsec/Free-RASP-Flutter/releases/tag/v6.10.0

Btw. If the iOS SDK version does not change, you can use the same dSYMs as for the previous version. You can find this info in the changelog, currently iOS SDK is version 6.6.3.

Regards,
Tomas

**Comment by JgomesAT** [comment]
I triad to upload  two days ago a version of my APP , and I had the warning when I finished to upload to apple store
