### ISSUE TITLE
Which callback is for cracked app with different app sign

### ISSUE THREAD

**Issue by yasaman93** [talsec/Free-RASP-Flutter#16]
I want to know if someone change my app and crack it with another app sign, which one of the callbacks will be called?

**Comment by talsec-app** [comment]
Hello @yasaman93 ,
cracked app with another signature is detectable via onTamperDetected (Android) and onSignatureDetected (iOS) callbacks. 

Check this wiki page section for more info: https://github.com/talsec/Free-RASP-Community/wiki/Threat-detection#app-tampering
