### ISSUE TITLE
Adroid Enterprise support

### ISSUE THREAD

**Issue by ITASerus** [talsec/Free-RASP-Flutter#18]
Does this library support android enterprise?

I'm using this library to write an app for this version of android and the devices are detected as tampered. 
The "non Android Enterprice" devices works correctly

If this library doesn't support this particular version of Android, will  support it in future?

**Comment by yakim333** [comment]
Hello, 

Are you asking about freeRASP or paid subscriptions?  I would prefer to discuss know more about particular use-cases, devices, etc. to make a decision about the prioritization of support for Enterprise Android.   

We have some products that can fit specific Business needs.

Please feel free to contact me via the https://www.talsec.app/contact

Have a good day.
Kind regards,
Sergiy Yakymchuk
Talsec

**Comment by talsec-app** [comment]
To support Sergiy, 

We haven't actually tested it, but we see no reason why the library shouldn't be supported on Android Enterprise. Android Enterprise could cause some issues by triggering onUntrustedInstallationDetected checks as there may be differences with APK distribution, but tamper checks shouldn't be affected. Could you please provide more information about your application (package name, watcher mail) so we can find which check exactly was triggered and provide an adequate solution? You can send the information privately to info@talsec.app.

Have a great day,
Talsec team
