### ISSUE TITLE
How to generate HASH_OF_YOUR_APP

### ISSUE THREAD

**Issue by prajwal27** [talsec/Free-RASP-Flutter#2]
The Readme file mentions HASH_OF_YOUR_APP
```
androidConfig: AndroidConfig(
        expectedPackageName: 'YOUR_PACKAGE_NAME',
        expectedSigningCertificateHash: 'HASH_OF_YOUR_APP',
        supportedAlternativeStores: ["com.sec.android.app.samsungapps"],
      ),
```
How do we generate this?

**Comment by talsec-app** [comment]
HASH_OF_YOUR_APP is a hash of the certificate of the key which was used to sign the application. This hash is then encoded in Base64 form.  
You can imagine it like: `base64(sha256(certificate))`  
To generate base64 form of hash, you can use [util functions provided for freeRASP for Android](https://github.com/talsec/Free-RASP-Android/blob/master/FreeRASPDemoApp/app/src/main/java/com/aheaditec/talsec/demoapp/Utils.kt).  
More about app signing [here](https://developer.android.com/studio/publish/app-signing).
