### ISSUE TITLE
Jailbreak detection bypass

### ISSUE THREAD

**Issue by AhmedAdel94** [talsec/Free-RASP-Flutter#27]
I used free rasp flutter package to detect jailbroken devices and it is working fine, however I can bypass the detection using the liberty lite tool, anyone has an idea how fix this issue?

**Comment by talsec-app** [comment]
Hello @AhmedAdel94 

Thank you for your report. We will take a closer look at this serious issue. We will post an update here when the investigation will be over.

Kind regards,
Talec Team

**Comment by talsec-app** [comment]
Hello @AhmedAdel94 ,
does the problem still occur?

Kind regards,
Talsec team
