### ISSUE TITLE
Warning on Play store when submitting builds with FreeRasp

### ISSUE THREAD

**Issue by sahildudeja-tide** [talsec/Free-RASP-Flutter#28]
When submitting app to the Play store with FreeRASP `v3.0.2` we get this warning regarding critical issue with play-services-safetynet `com.google.android.gms:play-services-safetynet:18.0.1`

![image](https://user-images.githubusercontent.com/89580256/190351762-6ce345f4-87c3-46e3-91cb-52bd6bd7b36c.png)

On investigating further we do see It's being included as a transitive dependency.

![image](https://user-images.githubusercontent.com/89580256/190352269-ee4da2d4-df8e-44df-afee-85fa70f4299b.png)

**Comment by talsec-app** [comment]
Hi @sahildudeja-tide ,

We are aware of this issue. The SafetyNet Attestation is being discontinued, Google plans to gradually turn down the SafetyNet Attestation API starting in June 2023. The SafetyNet Attestation API currently provides additional diagnostic data for our libraries, but we plan to migrate from SafetyNet API to the Play Integrity API in the near future. It should be done and released within the next version of the freeRASP. 

Kind regards,
Talsec Team

**Comment by yardexx** [comment]
Hello @sahildudeja-tide!

New version of freeRASP have been released. New version should fix this issue. 

Jaroslav from Talsec Team
