### ISSUE TITLE
Not receiving Watcher Alert emails

### ISSUE THREAD

**Issue by rakesh0689** [talsec/Free-RASP-Flutter#29]
I am using FreeRasp v3.0.2 on my Flutter app. Flutter version is 3.3.2 (as of today). I am not receiving any Watcher email alerts after updating the FreeRasp to version 3.0.0 and above on my Production as well as UAT builds. I was successfully receiving the alerts previously but after updating to 3.0.0, I stopped receiving the mails. I have correctly configured the watcher email field to my gmail as well, I have also written separate config for android and iOS as well. Still not receiving any mail, kindly help in solving the issue as I don't know what configuration error I have made (I have not changed the same from the beginning).
Is there a way to test the mail sending functionality?

**Comment by talsec-app** [comment]
Hello @rakesh0689 , we started to investigate the issue and try to fix it asap. We have a lead where the bug is already.

Kind regards,
Talsec team

**Comment by rakesh0689** [comment]
Thank you team @talsec-app for your quick reply and in working towards fixing the bug.

**Comment by rakesh0689** [comment]
Hello @talsec-app team, any update on this bug. Will there be any change that needs to be done on my app - as I am about to publish an update of my app today or tomorrow. If there is any change to be implemented at code level in my app i would need to hold the update release, hence asking.

**Comment by talsec-app** [comment]
Hello @rakesh0689 , please write us your watcherMail and package name at info@talsec.app , so we can verify if the logs are being sent correctly. Then, we can determine if there will be any changes needed at the code level.

**Comment by rakesh0689** [comment]
@talsec-app team, I have sent the mail to info@talsec.app. please check and revert. Thank you

**Comment by rakesh0689** [comment]
Dear @talsec-app team, today I received the Watcher alert email for both android as well as iOS. Please confirm whether the issue has been rectified or not. Thank you for solving the issue

**Comment by talsec-app** [comment]
Hello @rakesh0689 , the issue has been fixed. Thank you for notifying us about it!

Kind regards,
Talsec team

**Comment by rakesh0689** [comment]
Dear @talsec-app team,
I am using FreeRasp v3.0.2 on my Flutter app. Flutter version is 3.3.8 (as of today). As previously stated, I am not receiving any Watcher email alerts after 21/11/2022. I got the weekly alert mails until 21/11/2022 but haven't been receiving mails since then. Kindly help in solving the issue as I don't know what happened again, please take a look into the matter.
