### ISSUE TITLE
Get the status of check

### ISSUE THREAD

**Issue by rddewan** [talsec/Free-RASP-Flutter#30]
Hi,

Is there any way to listen to the checks that are going on . Like if the security check is started and completed , If we can listen to it then we can show a different UI based on the current status , like showing a loading screen when it's checking and showing a login screen when the checks are success and showing a error screen when check did not passed.

**Comment by talsec-app** [comment]
Hello @rddewan ,

Synchronous access was discussed in #20 . Unfortunately, such behavior is reserved for the business version only. Check the referenced issue for additional information.

Kind regards,
Talsec Team
