### ISSUE TITLE
Not receiving Watcher Email Alerts again !!!

### ISSUE THREAD

**Issue by rakesh0689** [talsec/Free-RASP-Flutter#37]

**Comment by rakesh0689** [comment]
Dear @talsec-app team,
I am using FreeRasp v3.0.2 on my Flutter app. Flutter version is 3.3.8 (as of today). As previously stated, I am not receiving any Watcher email alerts after 21/11/2022. I got the weekly alert mails until 21/11/2022 but haven't been receiving mails since then. Kindly help in solving the issue as I don't know what happened again, please take a look into the matter.

**Comment by talsec-app** [comment]
Hello @rakesh0689,
we will look into it promptly.

Kind regards,
Talsec team

**Comment by talsec-app** [comment]
Hello @rakesh0689 ,
the issue should be fixed. There was a problem with one of our services. The reports for last week were re-sent.

Kind regards,
Talsec team

**Comment by rakesh0689** [comment]
Dear @talsec-app team,

Thank you for fixing the issue. I received last weeks alert mail as well.
