### ISSUE TITLE
Swift Compiler Error (Xcode): No such module 'TalsecRuntime'

### ISSUE THREAD

**Issue by its-engineersindia** [talsec/Free-RASP-Flutter#39]
We have used Free-RASP-Flutter for our app. The Android build is working fine, but the iOS one gives the following error.

```
Swift Compiler Error (Xcode): No such module 'TalsecRuntime'
/Users/eil-its/flutter-sdk/.pub-cache/hosted/pub.dartlang.org/freerasp-3.0.2/ios/Classes/SwiftFreeraspPlugin.swift:2:7

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

Please advise.

**Comment by talsec-app** [comment]
Hello @its-engineersindia ,

1. Please Check if the **ios/.symlinks/plugins/freerasp/ios** contains **TalsecRuntime.xcframework** symlink. If not, create it manually in that folder using the following command:
`ln -s ./Debug/TalsecRuntime.xcframework/ TalsecRuntime.xcframework`
If there is no .symlinks folder, create the symlink in the **freerasp/ios** folder.

2. Run **pod install** in the application ios folder.

Kind regards,
Talsec team

**Comment by its-engineersindia** [comment]
Hello @talsec-app 

The symlink is already there. Please refer to the screenshot below.
<img width="478" alt="Screenshot 2022-12-13 at 5 06 01 PM" src="https://user-images.githubusercontent.com/80943994/207308224-7f4b8bbb-bbd5-484f-bf26-51d8b291d898.png">

**Comment by talsec-app** [comment]
Hello @its-engineersindia ,
could you try running **pod install** in the **application** ios folder again?
It could also be related to https://github.com/talsec/Free-RASP-Flutter/issues/22

Kind regards,
Talsec team

**Comment by its-engineersindia** [comment]
After a few cleans and refreshes, it started working. Thank you.
