### ISSUE TITLE
iOS build error, TalsecRuntime module not found

### ISSUE THREAD

**Issue by leopi99** [talsec/Free-RASP-Flutter#4]
On android works great, but on ios I can't build the app since won't find the TalsecRuntime module
here is the error:

```
    /Users/macbookpro/Documents/flutterSDK/.pub-cache/hosted/pub.dartlang.org/freerasp-1.0.0/ios/Classes/SwiftFreeraspPlugin.swift:3:8: error: no such module
    'TalsecRuntime'
    import TalsecRuntime
                ^
    /Users/macbookpro/Documents/flutterSDK/.pub-cache/hosted/pub.dartlang.org/freerasp-1.0.0/ios/Classes/SwiftFreeraspPlugin.swift:3:8: error: no such module
    'TalsecRuntime'
    import TalsecRuntime
                ^
```

**Comment by talsec-app** [comment]
We are sorry, but we were not able to reproduce your issue.
Cloud you please send us some sample app (for example basic counter app, etc.) that contains this issue? 
That would be really helpful.

**Comment by leopi99** [comment]
Creating a new app from scratch works without any problems

**Comment by source-code-hub** [comment]
This issue appears for me with Xcode 14 (macOS 13.4.1 (c))with Flutter 3.7.1. Looks like there is issue with the inclusion of Talsec framework. Please find the pod  structure under .syslink of iOS directory. I tried reinstalling Flutter, clean all cache but did not work.
<img width="395" alt="Screenshot 2023-07-28 at 12 15 02 PM" src="https://github.com/talsec/Free-RASP-Flutter/assets/15922724/365841b8-d06f-4f13-8786-e2490ba1f366">

**Comment by yardexx** [comment]
Hello.

May I ask what version of freeRASP are you using? Did you upgrade from older version or it's fresh install?

**Comment by generalprognostics** [comment]
It is a fresh install and freeRASP version is 4.0.0.

**Comment by source-code-hub** [comment]
It is a fresh install and freeRASP version is 4.0.0.

**Comment by source-code-hub** [comment]
I guess there is some issue while building iOS app with the freeRASP version 4.0.0 on MacOS 13.5 with Xcode 14.3.1.
I upgraded the freeRASP to version 6.0.0 and it worked.
