### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bugrevealingbme** [talsec/Free-RASP-Flutter#41]
I'm testing on Emulator, there is no error. There is no notification that it works. I put print everywhere, nothing happens. What is the problem. Android 12.

**Comment by bugrevealingbme** [comment]
No, I'm running in debug mode because I want to test it. I haven't tried release mode.

**Comment by bugrevealingbme** [comment]
There is no problem in release mode, it works. But I can't test it in debug.

**Comment by talsec-app** [comment]
Hello, this is by design of the dev vs release versions. See the https://github.com/talsec/Free-RASP-Flutter#dev-vs-release-version .. e.g., if a developer would like to kill the application running in an emulator, he would not be able to develop it using the emulator.
