### ISSUE TITLE
Some of the real devices Is consider as emulator

### ISSUE THREAD

**Issue by Joseph-Nathan** [talsec/Free-RASP-Flutter#48]
**Describe the bug**
i use the package in production and some of our user get  `onEmulatorDetected()`

**To Reproduce**
try to used the package in this device

**Expected behavior**
`onEmulatorDetected()` should not launch 

**Please complete the following information:**
 - Device: [ Samsung Galaxy A11 ]
 - Model: [ SM-A115F ]
 - OS version: [ Android 12 ]
 - Version of freeRASP: [ 4.0.0 ]
 - Users: [ 4 user ] 

**Additional context**
thanks for awesome work .

**Comment by msikyna** [comment]
Hello @Joseph-Nathan ,
we will look at the issue, thank you for reporting this!

Kind regards,
Matúš, Talsec developer

**Comment by SirionRazzer** [comment]
Hi @Joseph-Nathan ! 
Unfortunately, I couldn't find any false positive detections regarding that device model. I don't have any advice which would be helpful to you either. The emulator detection was recently updated, and the detection results have been pretty accurate. I would appreciate it if you could provide us with more details if the error occurs again in the future. You can use support@talsec.app to share nonpublic details (**package name, watcher email**).

**Comment by msikyna** [comment]
Hello @Joseph-Nathan ,
have there been more users experiencing the issue?

Kind regards,
Talsec team

**Comment by Joseph-Nathan** [comment]
Hi @msikyna  ,
yes , all user of Samsung Galaxy A11 
when they accept upgrade from Android 11 to Android 12 by Samsung
they face this ,
i now pass this device from the check ,

**Comment by yardexx** [comment]
Hello.

After carefully monitoring the situation for an extended period of time, we have determined that no issue is currently present with given device model.

Closing as wontfix.

Kind regards,
Jaroslav, Talsec developer
