### ISSUE TITLE
bug: onDebuggerDetected not working on debug mode or release mode

### ISSUE THREAD

**Issue by abdelrahman-abied** [talsec/Free-RASP-Flutter#50]

**Comment by msikyna** [comment]
Hello @abdelrahman-abied ,

thank you for reporting the issue! Could you add more details? E.g. device, model, os version, IDE, your environment, ... It works in our environment as expected.

Kind regards,
Matúš, Talsec dev

**Comment by abdelrahman-abied** [comment]
flutter version : 3.7.3
device : iphone 14 
ide :vscode
environment : mac os

**Comment by msikyna** [comment]
Could you verify, if you are running the Release version of the app? 
See https://github.com/talsec/Free-RASP-Flutter#dev-vs-release-version, https://github.com/talsec/Free-RASP-Flutter/issues/41
Is the onUnofficialStoreDetected? Are you running the application from Xcode? TestFlight?

**Comment by abdelrahman-abied** [comment]
> Could you verify, if you are running the Release version of the app? See https://github.com/talsec/Free-RASP-Flutter#dev-vs-release-version, #41 Is the onUnofficialStoreDetected? Are you running the application from Xcode? TestFlight?

yes i run the realease version

**Comment by msikyna** [comment]
Hello @abdelrahman-abied ,
could you show us how you integrated the callbacks? Is the onUnofficialStoreDetected? Are you running the application from Xcode? TestFlight?

**Comment by abdelrahman-abied** [comment]
With print statement

**Comment by msikyna** [comment]
Could you show us the whole integration of callbacks? Code snippet like the `initState()` from the Readme. Does the onUnofficialStoreDetected() work?

**Comment by yardexx** [comment]
Hello.

Were you able to resolve the issue? If not, could you provide information required by @msikyna?

Kind regards,
Jaroslav, Talsec developer
