### ISSUE TITLE
How this watcherMail work

### ISSUE THREAD

**Issue by abdelrahman-abied** [talsec/Free-RASP-Flutter#51]

**Comment by msikyna** [comment]
Hello @abdelrahman-abied ,

first, you path a mail address into the **watcherMail** parameter in **TalsecConfig**. Talsec registers this mail address and sends a regular (weekly) security reports describing the application's security state and characteristics of the devices it runs on, e.g. how many devices are rooted or if your application has been tampered. See the [Security Report](https://github.com/talsec/Free-RASP-Flutter#security-report) chapter for more details.

Kind regards,
Matúš, Talsec developer
