### ISSUE TITLE
bug: Use defaultTargetPlatform in order to test different cases with unit test

### ISSUE THREAD

**Issue by iastemesem** [talsec/Free-RASP-Flutter#61]
You Should use defaultTargetPlatform, in order to allow users to ovveride it with debugDefaultTargetPlatformOverride and test different cases, right now is impossibile to test due to we receive this standard error and we can't do nothing. 
`MissingPluginException(IOSconfig is not provided.)`

**Comment by yardexx** [comment]
Hello.

This issue is going to be resolved in an ongoing update.

Kind regards,
Jaroslav Novotný

**Comment by msikyna** [comment]
Hello @iastemesem  ,
could you try it with the new version? The version is `5.0.0`.

Kind regards,
Talsec team

**Comment by yardexx** [comment]
Hello,

New version fixes the issue. Can you let us know if the issue still persists for you?

Kind regards,
Talsec team
