### ISSUE TITLE
Talsec.instance.start does not complete

### ISSUE THREAD

**Issue by chimon2000** [talsec/Free-RASP-Flutter#67]
**Describe the bug**
When calling `await Talsec.instance.start(config)`, the initialization function never completes, causing the application to hang.

**To Reproduce**
Execute await Talsec.instance.start(config) during app start.

**Expected behavior**
The call either completes once Talsec starts or throws if there is an error.

**Screenshots**
n/a

**Please complete the following information:**
 - Device: iOS emulator
 - OS version: N/a
 - Version of freeRASP: 5.0.1

**Additional context**
n/a

**Comment by yardexx** [comment]
Hello, @chimon2000 

How do you create `TalsecConfig`? Do you create it using standard constructor or using `fromJson()` constructor?

**Comment by chimon2000** [comment]
Using the standard constructor.

**Comment by chimon2000** [comment]
If I don't await the `start` command then everything works fine. It's only when I do that the app hangs.

**Comment by yardexx** [comment]
Thank you for your input. Working on it!

**Comment by yardexx** [comment]
We released freeRASP 5.0.2 which fixes this issue. Update your pubspec.yaml to get a new version.
