### ISSUE TITLE
Threat detection order

### ISSUE THREAD

**Issue by reyesmfabian** [talsec/Free-RASP-Flutter#78]
Hi, 

Is there a way to set the order of threat detection?

We will set certain unique actions for each type of threat according to its severity. For example for "emulators" we will show a warning message, for others like "hooks" we will close the app.

We would like to know if there is a possibility to tell the SDK which threats to analyze first to avoid possible problems in UX, for example that the SDK detects the emulator and tries to show the message and then closes abruptly when it finds the hook.

**Comment by msikyna** [comment]
Hello @reyesmfabian,

currently, there is no way of setting the order of threat detection for freeRASP. The checks are performed asynchronously on Android, synchronously for iOS. If a check fails, the corresponding callback is executed.

However, in the BusinessRASP+, there is a way how to accomplish this. To see other differences between the freeRASP and businessRASP: https://github.com/orgs/talsec/discussions/5. 

If you would like to follow up on the topic, just pick a [time slot in Calendly](https://calendly.com/sergiy-yakymchuk-1/60min?month=2022-07).

Kind regards,
Talsec team

NB: If you are killing an application based on callbacks, make sure that it is done appropriately (e.g. see the https://stackoverflow.com/questions/45109557/flutter-how-to-programmatically-exit-the-app)
