### ISSUE TITLE
expectedSigningCertificateHash

### ISSUE THREAD

**Issue by Igormot** [talsec/Free-RASP-Flutter#8]
Hey guys.

I'm using such function to get the expectedSigningCertificateHash:
String encodedCert = base64.encode(utf8.encode('MY_SHA-256'));

expectedPackageName - the same value as in AndroidManifest.xml
supportedAlternativeStores - just an empty array ([])

But after I'm running the app in a release mode on the device I'm getting the next:
**MissingPluginException(No implementation found for method listen on channel plugins.aheaditec.com/events)
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506)**

For iOS, this lib works fine.

What can I do to make it work on Android too?

**Comment by talsec-app** [comment]
Hello.
Could you please provide full stacktrace (log) for given exception? 
Thanks in advance.

**Comment by talsec-app** [comment]
Hello.
We have just released new version of freeRASP which contains API nullchecks which should prevent invalid usage associated with crashes.
Talsec Team.

**Comment by Igormot** [comment]
Hi. I've switched to the new version 2.0.0 for a while but getting the new errors (checked Android version only). So, I've returned to 1.1.0

`lib/main.dart:224:7: Error: No named parameter with the name 'IOSConfig'.
      IOSConfig: IOSconfig(
      ^^^^^^^^^
../../../../../Library/Flutter/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/lib/talsec_config.dart:17:3: Context: Found this candidate, but the arguments don't match.
  TalsecConfig({
  ^^^^^^^^^^^^
lib/main.dart:263:7: Error: No named parameter with the name 'IOSCallback'.
      IOSCallback: IOScallback(
      ^^^^^^^^^^^
../../../../../Library/Flutter/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-2.0.0/lib/talsec_callback.dart:19:3: Context: Found this candidate, but the arguments don't match.
  TalsecCallback({
  ^^^^^^^^^^^^^^`

**Comment by Igormot** [comment]
@talsec-app that did the trick, thank you.
Now, with version 2.0.0 the lib working as expected - no more MissingPluginException messages. 

Thanks a lot, guys
