### ISSUE TITLE
Android app not compilable with AGP >= 8.0.0

### ISSUE THREAD

**Issue by HE-LU** [talsec/Free-RASP-Flutter#80]
**Describe the bug**
The app cannot be compiled when using AGP version 8.0.0 and higher.

**To Reproduce**
Create a new Flutter project, and update your classpath in the app gradle file to:
```
classpath 'com.android.tools.build:gradle:8.0.2'
```
and update your gradle wrapper to:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2.1-bin.zip
```

**Expected behavior**
App should compile

**Screenshots**
![image](https://github.com/talsec/Free-RASP-Flutter/assets/5673486/13f4ae78-4dd7-4d6b-b026-7113eb7e193a)

**Please complete the following information:**
 - Device: Emulator API 33
 - OS version: Android 13
 - Version of freeRASP: 6.1.0

**Additional context**
The libs Android project should probably be updated to AGP 8.0.0, and use a namespace instead of  applicationId

**Comment by msikyna** [comment]
Hello @HE-LU ,

thank you for reporting the issue, we will look at it!

Kind regards,
Talsec team

**Comment by xprikryl2** [comment]
Hi @HE-LU,

You are right. I've managed to reproduce this issue. We will release a new version with the fix soon. In the meantime, you can apply the fix yourself. 

Just navigate to the freeRASP folder in your dependencies (in Android Studio, you can find it in External dependencies -> Flutter plugins -> freerasp-6.1.0).
<img width="397" alt="image" src="https://github.com/talsec/Free-RASP-Flutter/assets/14791624/4579a904-da00-4e5e-be95-2c3274076958">
In the library root folder (freerasp-6.1.0), navigate to android -> build.gradle file. In this file, add `namespace 'com.aheaditec.freerasp'` at the beginning of the `android` section like shown here:
<img width="553" alt="image" src="https://github.com/talsec/Free-RASP-Flutter/assets/14791624/d7b890c7-5c08-4984-b76c-db34df564ee1">

It's a small change. I hope it will help you.

Best regards,
Talsec Team

**Comment by HE-LU** [comment]
@yardexx Hey, the namespace is there now. But there is still one more issue:
```
Incorrect package="com.aheaditec.freerasp" found in source AndroidManifest.xml: /home/helu/.pub-cache/hosted/pub.dev/freerasp-6.2.0/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.aheaditec.freerasp" from the source AndroidManifest.xml: /home/helu/.pub-cache/hosted/pub.dev/freerasp-6.2.0/android/src/main/AndroidManifest.xml.
```

I tried it locally, and it is still required to remove `package="com.aheaditec.freerasp"` from the Manifest file. After that, it is working fine ;)
