### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by bugrevealingbme** [talsec/Free-RASP-Flutter#83]
I want to migrate but I couldn't find the documentation. Why is it so hard? What is the new onTamperDetected name

**Comment by yardexx** [comment]
Hello.

Apologies for inconvenience caused during the migration process. 

Table that outlines the transition of old checks to their new merged callbacks:

Android old check | iOS old check | New merged check
-- | -- | --
onRootDetected | onJailbreakDetected | onPrivilegedAccess
onEmulatorDetected | onSimulatorDetected | onSimulator
onHookDetected | onRuntimeManipulationDetected | onHooks
onTamperDetected | onSignatureDetected | onAppIntegrity
onDeviceBindingDetected | onDeviceChangeDetected | onDeviceBinding
onUntrustedInstallationDetected | onUnofficialStoreDetected | onUnofficialStore
onDebuggerDetected | onDebuggerDetected | onDebug
_(not in 4.0.0 version)_ | onMissingSecureEnclaveDetected | onSecureHardwareNotAvailable
_(not available for this platform)_ | onDeviceIdDetected | onDeviceID
_(not in 4.0.0 version)_ | onPasscodeDetected | onPasscode
