### ISSUE TITLE
How the 100k limitation for free tier is calculated?

### ISSUE THREAD

**Issue by votruk** [talsec/Free-RASP-Flutter#86]
There are two limitations in the free tier:
1. **ppSec regular email reporting service** — yes (_up to 100k devices_)
2. **Mentioning the App name and logo in Talsec's marketing communications (e.g., "Trusted by" section on the web)** — _over 100k downloads_.

It is unclear how the 100k limitation in the free tier is applied in both cases.

For the _email reporting service_, as I understand, I should consider the total number of devices with the app that has freeRASP installed, correct? Then, what happens if I have more than 100k devices? Will the reporting stop functioning? Is it possible to opt out of the reporting entirely? In the current Flutter implementation, the watcherMail field is mandatory. Does this mean that trying the solution is not feasible if I have more than 100k users?

And what about _Mentioning the App name and logo in Talsec's marketing communications_? For example, if I have an app with 1 million downloads and I gain 50k new users every month, should I consider the total number of downloads of my app up to the moment of integrating freeRASP? Or do I have two months to use it before I reach 100k new users downloading the app?

All these questions arise from evaluating the "cost" of integrating the solution for the company I work for. Detailed explanations on these topics would be beneficial for all of us considering trying your solution.

**Comment by syakymchuk** [comment]
Hi @votruk ,

If you have more than 1M downloads, you are exceeding Fair Usage Policy of freeRASP and all the limitations are to be applied:
- The reporting function can be stopped but Data Collection will continue (for the product improvements and analytics)
- We may use your App brand in Talsec marketing communications.


This is done to encourage commercial users to switch to the commercial SDK of Talsec. It provides our customers a lot of security value on top of freeRASP basics.  Please take a look here: https://github.com/orgs/talsec/discussions/5

**Comment by yardexx** [comment]
Closed as resolved.
