### ISSUE TITLE
When the app is minimized and resumed before the checks, they do not occur.

### ISSUE THREAD

**Issue by GuilhermeDemoliner** [talsec/Free-RASP-Flutter#91]
Firstly, I want to thank the developers of the tool. This tool is highly significant for the Flutter community, and I hope the free version receives enhancements.
I am using the free version.
When I launch the app and quickly minimize it before the tool performs its checks, it seems that the checks are not carried out when the app is resumed.
The same happens in cases where the camera is opened before the checks.

**Expected behavior**
When minimizing and resuming the app after its launch, the FreeRasp tool should continue its security checks as usual.

 - Device: any
 - OS version: Android 12
 - Version of freeRASP: 6.3.0
 - Flutter Version: 3.13.4

**Comment by msikyna** [comment]
Hello @GuilhermeDemoliner ,

thank you for reporting this. We will look at it.

Kind regards,
Talsec team

**Comment by yardexx** [comment]
Hello.

I've checked it and I can confirm this issue. We'll develop and release fix as soon as we'll be able to.

Jaroslav from Talsec team

**Comment by yardexx** [comment]
Hello again.

We've managed to fix the issue. Fix will be released in upcoming version.

**Comment by Giovanny-DS** [comment]
@yardexx when will that version be release? do we can found it pulling directly from master?

**Comment by msikyna** [comment]
Hello @Giovanny-DS ,
the new version will be released this week.

Kind regards,
Talsec etam
