### ISSUE TITLE
only Xcode 13 required to be able to build the application.

### ISSUE THREAD

**Issue by AAbdulhameeD** [talsec/Free-RASP-Flutter#92]
**Describe the bug**
flutter newer versions requires a newer xcode versions , also publishing the app the App Store requires xcode version to be 14 at least.
so, how can I integrate the package with my project .
i'm using xcode 13.4 and it's too hard for me to downgrade it

**Comment by yardexx** [comment]
Hello!

Thank you for your input.

The note in the documentation that Xcode 13 is required is bit misleading. You can use Xcode 13 **or newer**, so Xcode 13.4 will work just fine. I personally use Xcode 14.3.1 without any issue. We'll clarify the note about Xcode version in upcoming release.

**Comment by DevAhmedRagab** [comment]
@yardexx 
I got this issue with my Xcode 13.4.1 and 13.0 when I tried to build the ios project

```
Failed to build module 'TalsecRuntime'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.
```

**Comment by yardexx** [comment]
That seems odd. We'll look into it.

**Comment by msikyna** [comment]
Hello, 
we will update the documentation for the minimum version of Xcode being 14.3 currently. The SDK is being built with newer versions of Xcode gradually. 

Is there any specific reason for not upgrading the Xcode? App Store submission gradually requires developers to update Xcode as well.

Kind regards,
Talsec team
