### ISSUE TITLE
onAppIntegrity after releasing playstore

### ISSUE THREAD

**Issue by naufalmms** [talsec/Free-RASP-Flutter#94]
when process debug, the application run normal and only shows onDebug check
but when released to playstore in testmode always get onAppIntegrity check

sha256 convert to base64 n package name already right value

how to solve it

**Comment by msikyna** [comment]
Hello @naufalmms ,
could you send us your watcherMail and package name at support@talsec.app? We will look at the data.

Kind regards,
Talsec team

**Comment by ribuemsyne** [comment]
@msikyna same for me also. When i uploaded my app for internal testing and installed it through playstore, it caught with appintegrity check. Need to comment on that check before uploading it in playstore. Any solution for this?

**Comment by msikyna** [comment]
Hello @ribuemsyne  ,
could you send us your watcherMail and package name at [support@talsec.app](mailto:support@talsec.app) as well? We will look at the data.

Kind regards,
Talsec team

**Comment by tajjacob** [comment]
I also have the same issue when upload to testflight app store connect and internal testing playstore console.
How to resolve this?

**Comment by tajjacob** [comment]
Hi @msikyna 

Thanks for the response.
I already send the requested info using email pmcareplus@pmcare.com.my.
Please have a look. 
Thanks again for your support
