### ISSUE TITLE
Android app not compilable with AGP >= 8.0.0

### ISSUE THREAD

**Issue by HE-LU** [talsec/Free-RASP-Flutter#97]
@yardexx Hey, the namespace is there now. But there is still one more issue:
```
Incorrect package="com.aheaditec.freerasp" found in source AndroidManifest.xml: /home/helu/.pub-cache/hosted/pub.dev/freerasp-6.2.0/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.aheaditec.freerasp" from the source AndroidManifest.xml: /home/helu/.pub-cache/hosted/pub.dev/freerasp-6.2.0/android/src/main/AndroidManifest.xml.
```

I tried it locally, and it is still required to remove `package="com.aheaditec.freerasp"` from the Manifest file. After that, it is working fine ;)

_Originally posted by @HE-LU in https://github.com/talsec/Free-RASP-Flutter/issues/80#issuecomment-1698716928_

**Comment by SirionRazzer** [comment]
Thank you for bringing this up. I will check with the team if this is fixed in the next release which is being finalized. I will update you as soon as I can.

**Comment by HE-LU** [comment]
More info and proof:
![image](https://github.com/talsec/Free-RASP-Flutter/assets/5673486/f7c4f637-b2c6-4ff0-8d4f-80f5b97e2343)
